
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: mbeng44/worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mbeng44/worker
  template:
    metadata:
      labels:
        app: mbeng44/worker
    spec:
      containers:
      - name: woker
        image: mbeng44/worker:latest
        ports:
        - containerPort: 80

